# 
[webservers]
# 替換成你的伺服器 IP
# ansible_user: 遠端登入的使用者名稱
# ansible_ssh_private_key_file: 你的 SSH Key 路徑 (專業工程師不使用密碼登入)
sentient_prod ansible_host=192.168.50.150 ansible_user=prometheus ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
# 這裡定義所有機器通用的變數
ansible_python_interpreter=/usr/bin/python3